### ISSUE TITLE
Parent permission nodes do not enable permissions

### ISSUE THREAD

**Issue by JCox06** [MockBukkit/MockBukkit#612]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest version of MockBukkit?

- [X] I am using the latest version of MockBukkit.

### Minecraft Version

1.19

### Describe the bug

I have tested on mockbukkit mc versions 1.16 and 1.19
When using the Player#addAttachment with a permission that is a parent of other nodes it does not enable them permissions.

For example take the permission myplugin.* that is the parent of all other permission in the plugin
When adding the attachment myplugin.* the child node permissions will not be enabled

### Reproducible Test

1) Make your plugin yaml have child permissions. For example
```yml
permissions:
  myplugin.*:
    description: Gives access to all permissions
    children:
      myplugin.reload: true
      myplugin.use: true
      myplugin.enable: true
```

2) Add the attachment during testing `myplugin.*` to the player object

3) When trying to complete an action that requires the permissions reload, use, or enable, they will not work. The player will be sent the message: "I'm sorry, but you do not have permission to perform this command"

**Comment by Insprill** [comment]
Is this still an issue? We've switched to using `PermissibleBase` for permission handling which is what CraftBukkit uses; so I'm not sure what would be causing this.

**Comment by JCox06** [comment]
Yes, I have just tested it with version 2.117.2 and MockBukkit won't enable the child permissions.

I have also tested adding permissions in a paper server. As you would expect the server does correctly give the child permissions to the player. So it is not that my yaml is incorrect.

**Comment by Insprill** [comment]
Can you provide a test to reproduce this issue?

**Comment by JCox06** [comment]
Sorry, I don't quite understand. I assume this is the test you want: I have one command that when executed with the correct permission will add a player to List. The first test will fail, but the second one will pass successfully.

```java
//Check if the player can perform a command, that when executed adds them to a list
    @Test
    public void playerAddedToListWithParentPermission() {
        PlayerMock player = server.addPlayer();
        player.addAttachment(plugin, "permtest.*", true);
        player.performCommand("test");
        System.out.println(player.nextMessage());
        assertTrue(plugin.isInList(player)); //Test Fails
    }

    //Check if the player can perform a command, that when executed adds them to a list
    @Test
    public void playerAddedToListWithSpecificPermission() {
        PlayerMock player = server.addPlayer();
        player.addAttachment(plugin, "permtest.child", true);
        player.performCommand("test");
        System.out.println(player.nextMessage());
        assertTrue(plugin.isInList(player)); //Test success
    }
```

Plugin.yml
```yaml
permissions:
  permtest.*:
    description: Give access to all permissions
    default: op
    children:
      permtest.child: true
  permtest.child:
    description: Gives access to test command
    default: op
```

Thank you.
